server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: multiplication
          uri:
            lb://MULTIPLICATION
          predicates:
          - Path= /multiplications/**, /results/**
        - id: gamification
          uri:
            lb://GAMIFICATION
          predicates:
          - Path= /leaders/**, /stats/**

      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "http://localhost:9090"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/